var oval = document.querySelector('#oval')
var control = false;
oval.onclick = nightmode
document.querySelectorAll('label')[1].style.color = '#6E8098'
document.querySelectorAll('label')[2].style.color = '#6E8098'
document.querySelectorAll('label')[3].style.color = '#6E8098'
document.querySelectorAll('label')[4].style.color = '#6E8098'
document.querySelectorAll('label')[5].style.color = '#6E8098'
document.querySelectorAll('label')[6].style.color = '#6E8098'
document.querySelectorAll('label')[7].style.color = '#6E8098'
document.querySelectorAll('label')[8].style.color = '#6E8098'
document.querySelectorAll('label')[9].style.color = '#6E8098'
document.querySelectorAll('label')[10].style.color = '#6E8098'
document.querySelectorAll('label')[11].style.color = '#6E8098'
document.querySelectorAll('label')[12].style.color = '#6E8098'
document.querySelectorAll('label')[13].style.color = '#6E8098'
document.querySelectorAll('label')[14].style.color = '#6E8098'
document.querySelectorAll('label')[15].style.color = '#6E8098'
document.querySelectorAll('label')[16].style.color = '#6E8098'
document.querySelectorAll('label')[17].style.color = '#6E8098'
document.querySelectorAll('label')[18].style.color = '#6E8098'
document.querySelectorAll('label')[19].style.color = '#6E8098'
document.querySelectorAll('label')[20].style.color = '#6E8098'
document.querySelectorAll('label')[21].style.color = '#6E8098'
document.querySelectorAll('label')[22].style.color = '#6E8098'
document.querySelectorAll('label')[23].style.color = '#6E8098'
document.querySelectorAll('label')[24].style.color = '#6E8098'
document.querySelectorAll('label')[25].style.color = '#6E8098'
document.querySelectorAll('label')[26].style.color = '#6E8098'
document.querySelectorAll('label')[27].style.color = '#6E8098'
document.querySelectorAll('label')[28].style.color = '#6E8098'
document.querySelectorAll('label')[29].style.color = '#6E8098'
document.querySelectorAll('label')[30].style.color = '#6E8098'
document.querySelectorAll('label')[31].style.color = '#6E8098'
document.querySelectorAll('label')[32].style.color = '#6E8098'
document.querySelectorAll('label')[33].style.color = '#6E8098'
document.querySelectorAll('label')[34].style.color = '#6E8098'
document.querySelectorAll('label')[35].style.color = '#6E8098'
document.querySelectorAll('label')[36].style.color = '#6E8098'
function nightmode() {
	if (control) {
oval.style.marginLeft = '4px'
document.querySelector('.block1').style.backgroundColor = 'white'
document.querySelector('.block2').style.backgroundColor = 'white'
document.querySelector('.block3').style.backgroundColor = 'white'
document.querySelector('.block4').style.backgroundColor = 'white'
document.querySelector('.block5').style.backgroundColor = 'white'
document.querySelector('.block6').style.backgroundColor = 'white'
document.querySelector('.block7').style.backgroundColor = 'white'
document.querySelector('.block8').style.backgroundColor = 'white'
document.querySelector('.block9').style.backgroundColor = 'white'
document.querySelector('.block10').style.backgroundColor = 'white'
document.querySelector('.block11').style.backgroundColor = 'white'
document.querySelector('.block12').style.backgroundColor = 'white'
document.querySelector('body').style.backgroundColor = ''
document.querySelector('#Filter-bar').style.backgroundColor = ''
document.querySelector('#location-bar').style.backgroundColor = ''
document.querySelector('#search').style.backgroundColor = ''
document.getElementById('search-bar').style.backgroundColor = ''
document.querySelector('#Filter-input').style.backgroundColor = ''
document.querySelector('#Filter-input').style.color = ''
document.querySelector('#location-input').style.color = ''
document.querySelector('#location-input').style.backgroundColor = ''
document.querySelectorAll('h2')[0].style.color = ''
document.querySelectorAll('h2')[1].style.color = ''
document.querySelectorAll('h2')[2].style.color = ''
document.querySelectorAll('h2')[3].style.color = ''
document.querySelectorAll('h2')[4].style.color = ''
document.querySelectorAll('h2')[5].style.color = ''
document.querySelectorAll('h2')[6].style.color = ''
document.querySelectorAll('h2')[7].style.color = ''
document.querySelectorAll('h2')[8].style.color = ''
document.querySelectorAll('h2')[9].style.color = ''
document.querySelectorAll('h2')[10].style.color = ''
document.querySelectorAll('h2')[11].style.color = ''
document.querySelector('#top-image').style.border = ''
document.querySelector('#fulltimetxt').style.color = ''

control = !control
	} else {
		oval.style.marginLeft = '30px'
document.querySelector('.block1').style.backgroundColor = '#19202D'
document.querySelector('.block2').style.backgroundColor = '#19202D'
document.querySelector('.block3').style.backgroundColor = '#19202D'
document.querySelector('.block4').style.backgroundColor = '#19202D'
document.querySelector('.block5').style.backgroundColor = '#19202D'
document.querySelector('.block6').style.backgroundColor = '#19202D'
document.querySelector('.block7').style.backgroundColor = '#19202D'
document.querySelector('.block8').style.backgroundColor = '#19202D'
document.querySelector('.block9').style.backgroundColor = '#19202D'
document.querySelector('.block10').style.backgroundColor = '#19202D'
document.querySelector('.block11').style.backgroundColor = '#19202D'
document.querySelector('.block12').style.backgroundColor = '#19202D'
document.querySelector('body').style.backgroundColor = '#121721'
document.querySelector('#Filter-bar').style.backgroundColor = '#19202D'
document.querySelector('#location-bar').style.backgroundColor = '#19202D'
document.querySelector('#search').style.backgroundColor = '#19202D'
document.getElementById('search-bar').style.backgroundColor = 'grey'
document.querySelector('#Filter-input').style.backgroundColor = '#19202D'
document.querySelector('#Filter-input').style.color = 'white'
document.querySelector('#location-input').style.color = 'white'
document.querySelector('#location-input').style.backgroundColor = '#19202D'
document.querySelectorAll('h2')[0].style.color = 'white'
document.querySelectorAll('h2')[1].style.color = 'white'
document.querySelectorAll('h2')[2].style.color = 'white'
document.querySelectorAll('h2')[3].style.color = 'white'
document.querySelectorAll('h2')[4].style.color = 'white'
document.querySelectorAll('h2')[5].style.color = 'white'
document.querySelectorAll('h2')[6].style.color = 'white'
document.querySelectorAll('h2')[7].style.color = 'white'
document.querySelectorAll('h2')[8].style.color = 'white'
document.querySelectorAll('h2')[9].style.color = 'white'
document.querySelectorAll('h2')[10].style.color = 'white'
document.querySelectorAll('h2')[11].style.color = 'white'
document.querySelector('#fulltimetxt').style.color = 'white'
document.querySelector('#top-image').style.border = '#121721 solid 1px'
control = !control
	}


}
	

var filter = document.querySelector('#filter-logo')
var control1 = true;
filter.onclick = displaymode

function displaymode() {
	if (control1) {

document.querySelector('.block1').style.display = 'none'
document.querySelector('.block2').style.display = 'none'
document.querySelector('.block3').style.display = 'none'
document.querySelector('.block4').style.display = 'none'
document.querySelector('.block5').style.display = 'none'
document.querySelector('.block6').style.display = 'none'
document.querySelector('.block7').style.display = 'none'
document.querySelector('.block8').style.display = 'none'
document.querySelector('.block9').style.display = 'none'
document.querySelector('.block10').style.display = 'none'
document.querySelector('.block11').style.display = 'none'
document.querySelector('.block12').style.display = 'none'
control1 = !control1

	} else {
document.querySelector('.block1').style.display = ''
document.querySelector('.block2').style.display = ''
document.querySelector('.block3').style.display = ''
document.querySelector('.block4').style.display = ''
document.querySelector('.block5').style.display = ''
document.querySelector('.block6').style.display = ''
document.querySelector('.block7').style.display = ''
document.querySelector('.block8').style.display = ''
document.querySelector('.block9').style.display = ''
document.querySelector('.block10').style.display = ''
document.querySelector('.block11').style.display = ''
document.querySelector('.block12').style.display = ''
control1 = !control1
}
}

